Namespace LanguageExtensions
    ''' <summary>
    ''' Several language method extensions used to create data relations
    ''' between two tables. 
    ''' </summary>
    ''' <remarks>
    ''' The idea is more to hide the code which creates the relations from
    ''' our regular code.
    ''' </remarks>
    Public Module DataRelationsExtensions
        ''' <summary>
        ''' Wrapper to create a master detail relationship
        ''' </summary>
        ''' <param name="dataSet">Populated DataSet</param>
        ''' <param name="masterTableName">Parent table</param>
        ''' <param name="childTableName">Child table</param>
        ''' <param name="keyColumn">Common field linking master to child</param>
        ''' <remarks>
        ''' Relationship name is generated by concatenating the master and child
        ''' table names together
        ''' </remarks>
        <DebuggerStepThrough()>
        <Runtime.CompilerServices.Extension()>
        Public Sub SetRelation(
                               dataSet As DataSet,
                               masterTableName As String,
                               childTableName As String,
                               keyColumn As String)

            dataSet.Relations.Add(
                New DataRelation(String.Concat(masterTableName, childTableName),
                                 dataSet.Tables(masterTableName).Columns(keyColumn),
                                 dataSet.Tables(childTableName).Columns(keyColumn)
                                 )
                )

        End Sub
        ''' <summary>
        ''' Wrapper to create a master detail relationship
        ''' </summary>
        ''' <param name="dataSet">Populated DataSet</param>
        ''' <param name="masterTableName">Parent table</param>
        ''' <param name="childTableName">Child table</param>
        ''' <param name="keyColumn">Common field linking master to child</param>
        ''' <param name="name">Relationship name</param>
        ''' <remarks></remarks>
        <DebuggerStepThrough()>
        <Runtime.CompilerServices.Extension()>
        Public Sub SetRelation(dataSet As DataSet, masterTableName As String, childTableName As String, keyColumn As String, name As String)
            dataSet.Relations.Add(
                New DataRelation(name,
                                 dataSet.Tables(masterTableName).Columns(keyColumn),
                                 dataSet.Tables(childTableName).Columns(keyColumn)
                                 )
                )
        End Sub

    End Module
End Namespace