'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------



'INSTANT C# NOTE: Formerly VB project-level imports:
Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Data
Imports System.Drawing
Imports System.Diagnostics
Imports System.Windows.Forms
Imports System.Linq
Imports System.Xml.Linq
Imports System.Threading.Tasks

Namespace EnumerateFilesAsync
	Namespace My

		'NOTE: This file is auto-generated; do not modify it directly.  To make changes,
		' or if you encounter build errors in this file, go to the Project Designer
		' (go to Project Properties or double-click the My Project node in
		' Solution Explorer), and make changes on the Application tab.
		'
		Partial Friend Class MyApplication
			Inherits ApplicationServices.WindowsFormsApplicationBase

			<System.Diagnostics.DebuggerStepThroughAttribute()>
			Public Sub New()
				MyBase.New(ApplicationServices.AuthenticationMode.Windows)
				Me.IsSingleInstance = False
				Me.EnableVisualStyles = True
				Me.SaveMySettingsOnExit = True
				Me.ShutdownStyle = ApplicationServices.ShutdownMode.AfterMainFormCloses
			End Sub

			<System.Diagnostics.DebuggerStepThroughAttribute()>
			Protected Overrides Sub OnCreateMainForm()
                Me.MainForm = Global.Form1.DefaultInstance
            End Sub

			Private Shared MyApp As MyApplication
			Friend Shared ReadOnly Property Application() As MyApplication
				Get
					Return MyApp
				End Get
			End Property

			<STAThread>
			Shared Sub Main(ByVal args() As String)
				MyApp = New MyApplication()
				MyApp.Run(args)
			End Sub

		End Class
	End Namespace

End Namespace