'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------



'INSTANT C# NOTE: Formerly VB project-level imports:
Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Data
Imports System.Drawing
Imports System.Diagnostics
Imports System.Windows.Forms
Imports System.Linq
Imports System.Xml.Linq
Imports System.Threading.Tasks

Namespace EnumerateFilesAsync
	Namespace My.Resources

		'This class was auto-generated by the StronglyTypedResourceBuilder
		'class via a tool like ResGen or Visual Studio.
		'To add or remove a member, edit your .ResX file then rerun ResGen
		'with the /str option, or rebuild your VS project.
		'''<summary>
		'''  A strongly-typed resource class, for looking up localized strings, etc.
		'''</summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
		Friend Module Resources

			Private resourceMan As System.Resources.ResourceManager

			Private resourceCulture As System.Globalization.CultureInfo

			'''<summary>
			'''  Returns the cached ResourceManager instance used by this class.
			'''</summary>
			<System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>
			Friend ReadOnly Property ResourceManager() As System.Resources.ResourceManager
				Get
					If Object.ReferenceEquals(resourceMan, Nothing) Then
						Dim temp As New System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
						resourceMan = temp
					End If
					Return resourceMan
				End Get
			End Property

			'''<summary>
			'''  Overrides the current thread's CurrentUICulture property for all
			'''  resource lookups using this strongly typed resource class.
			'''</summary>
			<System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>
			Friend Property Culture() As System.Globalization.CultureInfo
				Get
					Return resourceCulture
				End Get
				Set(ByVal value As System.Globalization.CultureInfo)
					resourceCulture = value
				End Set
			End Property
		End Module
	End Namespace

End Namespace